# -*- coding: utf-8 -*-
"""desafio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_oMmK-w1485sD5xvbIjq30wqg8n-aiQf
"""

import pandas as pd
import numpy as np

# Importando DataSet
df = pd.read_csv('https://pycourse.s3.amazonaws.com/bike-sharing.csv')

# Tamanho do Dataset
df.shape

# Media da coluna Windspeed
df['windspeed'].mean()

# Media da coluna temp
df['temp'].mean()

# Quantidade de registros para 2011
len(df.loc[df['year'] == 0])

# Quantidade de registros para 2012
len(df.loc[df['year'] == 1])

# Quantas locações foram registradas para 2011
df.loc[df['year'] == 0]['total_count'].sum()

# Quantas locações foram registradas para 2012
df.loc[df['year'] == 1]['total_count'].sum()

# Qual estação do ano possui a maior média de locações
df.groupby(by = ['season'])['total_count'].mean().sort_values(ascending = False).head(1)

# Qual estação do ano possui a menor média de locações
df.groupby(by = ['season'])['total_count'].mean().sort_values(ascending = True).head(1)

# Qual horario do dia possui a maior media de locacao
df.groupby(by = ['hour'])['total_count'].mean().sort_values(ascending = False).head(1)

# Qual horario do dia possui a menor media de locacao
df.groupby(by = ['hour'])['total_count'].mean().sort_values(ascending = True).head(1)

# Qual dia da semana possui a maior média de locações
df.groupby(by = ['weekday'])['total_count'].mean().sort_values(ascending = False).head(1)

# Qual dia da semana possui a menor média de locações
df.groupby(by = ['weekday'])['total_count'].mean().sort_values(ascending = True).head(1)

# As quartas feiras, qual é o horario do dia tem a maior media de locação
df.loc[df['weekday'] == 3].groupby(by = ['hour'])['total_count'].mean().sort_values(ascending = False).head(1)

# Aos sabados feiras, qual é o horario do dia tem a maior media de locação
df.loc[df['weekday'] == 6].groupby(by = ['hour'])['total_count'].mean().sort_values(ascending = False).head(1)